SHOW DATABASES;

-- DB_MEMBER1115

CREATE DATABASE DB_MEMBER1115;
USE DB_MEMBER1115;

CREATE TABLE TBL_MEMBER (
	M_NO 				INT AUTO_INCREMENT, 
    M_ID 				VARCHAR(20) UNIQUE, 
    M_PW 				VARCHAR(100) NOT NULL, 
    M_MAIL 				VARCHAR(50) NOT NULL, 
    M_PHONE 			VARCHAR(50) NOT NULL, 
    M_PROFILE_THUM 		VARCHAR(50) NOT NULL, 
    M_REG_DATE 			DATETIME DEFAULT NOW(), 
    M_MOD_DATE 			DATETIME DEFAULT NOW(),
    M_ROLE				VARCHAR(20) DEFAULT 'PRE_USER', 
    PRIMARY KEY(M_NO)
    );
    
    SELECT * FROM TBL_MEMBER;